#!/usr/bin/env ruby

def sh(cmd)
    puts cmd
    system cmd
end

name = ARGV[0] || "test-babel"

sh "mkdir -p #{name}/src"
sh "mkdir -p #{name}/target"

# ES2015转码规则
sh "cd #{name};npm install --save-dev babel-preset-es2015 --registry=https://registry.npm.taobao.org"

# react转码规则
sh "cd #{name};npm install --save-dev babel-preset-react --registry=https://registry.npm.taobao.org"

# ES7不同阶段语法提案的转码规则（共有4个阶段），选装一个
#$ npm install --save-dev babel-preset-stage-0
#$ npm install --save-dev babel-preset-stage-1
sh "cd #{name};npm install --save-dev babel-preset-stage-2 --registry=https://registry.npm.taobao.org"
#$ npm install --save-dev babel-preset-stage-3

sh "cd #{name};npm install --save-dev babel-cli --registry=https://registry.npm.taobao.org"


bcontent = <<-eos
{
    "presets": [
        "es2015",
        "react",
        "stage-2"
    ],
    "plugins": []
}

eos

File.write "#{name}/.babelrc", bcontent

pcontent = <<-eos
{
  "devDependencies": {
    "babel-cli": "^6.0.0"
  },
  "scripts": {
    "build": "babel src -d target"
  }
}

eos

File.write "#{name}/package.json", pcontent


ccontent = <<-eos

var arr = [1,2,3];
var ret = arr.map(item => item + 1);
console.log(ret);

eos

File.write "#{name}/src/main.js", ccontent


icontent = <<-eos

target
node_modules

eos

rcontent = <<-eos
task :default do
  sh 'rake -T'
end

desc 'build'
task :build do
  sh 'npm run build'
end

desc 'run'
task run: :build do
  sh 'node target/main.js'
end

eos

File.write "#{name}/Rakefile", rcontent
