#!/bin/bash

function seagull() {
  # https://github.com/tobegit3hub/seagull
  docker run -d -p 10086:10086 -v /var/run/docker.sock:/var/run/docker.sock tobegit3hub/seagull
}

case "$1" in
  seagull)
    seagull;;
  *)
    echo seagull;;
esac
