#!/usr/bin/env python

import os
import sys
import subprocess

dir_path = os.getcwd()  # os.path.dirname(os.path.realpath(__file__))

if len(sys.argv) == 1:
    print 'GOPATH={} go '.format(dir_path)
else:
    args = ' '.join(sys.argv[1:])
    cmd = 'GOPATH={} {}'.format(dir_path, args)
    print cmd

    subprocess.call(cmd, shell=True)
