#!/usr/bin/env ruby

name = ARGV[0] || "test_go"
PDIR = ENV['GOPATH'] + "/src"

TARGET_DIR = "#{PDIR}/#{name}"

raise "dir existing: #{TARGET_DIR}" if Dir.exists?(TARGET_DIR)

def sh(cmd)
  puts cmd
  ret = system cmd
  raise 'error' unless ret
end

sh "mkdir -p #{TARGET_DIR}"
sh "cd #{TARGET_DIR};glide init"

main_content = <<eos
package main

import (
  "fmt"
)

func main() {
  fmt.Println("Hello, World!")
}

eos

File.write("#{TARGET_DIR}/main.go", main_content)

ignore_content = <<eos
vendor/
tmp/

*.pyc

eos

File.write("#{TARGET_DIR}/.gitignore", ignore_content)

sh "cd #{TARGET_DIR};go fmt ./..."

sh "tree #{TARGET_DIR}"

puts "Finished!"

puts "just cd #{TARGET_DIR}"
