urls = [
     "http://bbs.szhome.com/30017.html",
     "https://discord.com/channels/@me",
     "https://twitter.com",
     "http://www.douban.com",
     "http://www.weibo.com",
     #"http://www.deftype.com",
     "http://www.oschina.net/",
     #"http://www.infoq.com/",
     "http://www.infoq.com/cn",
     "https://www.infoq.cn/topic/architecture",
     "https://www.infoq.cn/topic/CloudNative",
     "https://www.infoq.cn/topic/cloud-computing",
     "https://www.infoq.cn/topic/programing-languages",
     "http://36kr.com/",
     "https://news.ycombinator.com/news",
     "https://github.com/stars?direction=desc&sort=updated",
     #"https://blog.appsignal.com/",
     #"https://elixirstatus.com/",
     "https://elixirforum.com/",
     #"https://github.com/trending/elixir",
     "https://github.com/trending",
     #"https://github.com/trending/lua?since=daily",
     #"https://github.com/trending/ruby?since=daily",
     "https://github.com/trending/typescript?since=daily",
     "https://www.reddit.com/r/golang/",
     "https://github.com/trending/go?since=daily",
     #"https://github.com/trending/kotlin?since=daily",
     "https://github.com/trending/java?since=daily",
     "https://github.com/trending/scala?since=daily",
     "https://gitter.im/rustpython/Lobby",
     "https://github.com/trending/python?since=daily",
     #"https://reasonml.chat/",
     #"https://www.reddit.com/r/reasonml/",
     "https://www.reddit.com/r/scala/",
     "https://gitter.im/lampepfl/dotty",
     "https://gitter.im/scala-js/scala-js",
     "https://gitter.im/scala-native/scala-native",
     "https://rustcc.cn/section?id=f4703117-7e6b-4caf-aa22-a3ad3db6898f",
     "https://github.com/trending/rust?since=daily",
     "https://www.reddit.com/r/rust",
     "https://lobste.rs/",
]
