urls = [
     "http://bbs.szhome.com/30017.html",
     "https://twitter.com",
    
     "http://www.douban.com",
     "http://www.weibo.com",
     "http://www.deftype.com",
     "http://www.oschina.net/",
     #"http://www.infoq.com/",
     "http://www.infoq.com/cn",
     "http://36kr.com/",
     "https://news.ycombinator.com/news",

      "https://github.com/stars?direction=desc&sort=updated",
     #"https://blog.appsignal.com/",
     #"https://elixirstatus.com/",
     "https://elixirforum.com/",
     #"https://github.com/trending/elixir",
     "https://github.com/trending",
     "https://github.com/trending/lua?since=daily",
     "https://github.com/trending/ruby?since=daily",
     "https://github.com/trending/typescript?since=daily",
     "https://www.reddit.com/r/golang/",
     "https://github.com/trending/go?since=daily",
     "https://github.com/trending/kotlin?since=daily",
     "https://github.com/trending/java?since=daily",
     "https://github.com/trending/scala?since=daily",
     #"https://github.com/trending/python",
     #"https://reasonml.chat/",
     #"https://www.reddit.com/r/reasonml/",
     "https://github.com/trending/rust",
     "https://www.reddit.com/r/rust"
]
