#!/usr/bin/env ruby

class String
  def browser(f=false)
    cmd = case
      when  RbConfig::CONFIG['host_os'] =~ /linux|bsd/
        'xdg-open'
      when RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/
        'start'
      when RbConfig::CONFIG['host_os'] =~ /darwin/
        'open'
    end
    if cmd
      cline = "#{cmd} #{self} > /dev/null 2>&1" + (f ? "" : " &")
      puts cline
      system cline
      if f
        sleep(0.3)
      end
    end
  end
end

if __FILE__ == $0
  f = ARGV.any? { |e| e.start_with? "--f" }
  %w[https://twitter.com/
    https://github.com/manastech/crystal
    http://www.reddit.com/r/crystal_programming
    https://groups.google.com/forum/?fromgroups#!forum/crystal-lang
    https://github.com/stars?direction=desc&sort=updated
    https://github.com/notifications
    http://getprismatic.com
    http://www.douban.com
    http://www.weibo.com
    http://www.deftype.com
    http://www.haoshuju.net:8000
    http://www.adexchanger.cn
    http://www.rtbchina.com
    http://bbs.szhome.com/30017.html
  ].reverse
   .map {|url| %Q("#{url}")}
   .each {|url| url.browser(f)}
end
