#!/bin/bash

function to_java() {
  version=$1
  cd ~/dev-env
  rm java
  ln -s "java${version}" java
  java -version
}

function usage() {
  java -version
  echo "jvm 7|8"
}

case "$1" in
  7) to_java 7;;
  8) to_java 8;;
  *) usage;;
esac
