#!/usr/bin/env python

# pylint: disable=C0103
# pylint: disable=C0111

# pip install pytoml
# pip install pyfunctional

#import os
import subprocess


def open_browser(url: str, cmd: str = 'x-www-browser'):
    #os.system('%s %s > /dev/null 2>&1 &' % (cmd, url))
    subprocess.Popen([cmd, url], stdout=subprocess.DEVNULL,
                     stderr=subprocess.DEVNULL)


if __name__ == '__main__':
    import pytoml as toml
    import os.path
    #from functional import seq

    TOML_FILE = 'jiayou.toml'
    toml_file = os.path.join(os.path.dirname(__file__), TOML_FILE)
    print('load urls from %s...' % toml_file)

    with open(toml_file, 'rb') as f:
        config = toml.load(f)
        for url in config['urls']:
            open_browser(url)
        # seq(obj['urls']).for_each(open_browser)

        # for url in obj['urls']:
        #    os.system('xdg-open {}'.format(url))
        # subprocess.call("xdg-open {}".format(url), shell=True)
