#!/usr/bin/env python

# pylint: disable=C0103
# pylint: disable=C0111

# pip install pytoml
# pip install pyfunctional

import subprocess
from os import path


def open_browser(url: str, cmd: str = 'x-www-browser'):
    subprocess.Popen([cmd, url], stdout=subprocess.DEVNULL,
                     stderr=subprocess.DEVNULL)


if __name__ == '__main__':
    import pytoml as toml
    import os.path
    #from functional import seq

    TOML_FILE = 'jiayou.toml'
    toml_file = path.join(os.path.dirname(__file__), TOML_FILE)
    print(f'load urls from {toml_file}...')

    with open(toml_file, 'rb') as f:
        config = toml.load(f)
        for url in config['urls']:
            print(f'open {url}...')
            open_browser(url)
        # seq(obj['urls']).for_each(open_browser)
