#!/usr/bin/env ruby

KOTLIN_VERSION='1.0.0-beta-4583'

name = ARGV[0] || "test-kotlin"

def sh(cmd)
  puts cmd
  ret = system cmd
  raise "error" unless ret
end


################################################################################
sh "mkdir #{name}"

['java', 'resources', 'kotlin'].each do |x|
  sh "mkdir -p #{name}/src/main/#{x}"
end

sh "cd #{name}; gradle init"

build_content = <<-eos
buildscript {
    project.ext.kotlin_version = '#{KOTLIN_VERSION}'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: "kotlin"
apply plugin: 'application'

repositories {
    maven {
        url "http://www.haoshuju.net:8078/"
    }
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    //compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    //compile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
}

sourceSets {
    main.kotlin.srcDirs += 'src/main/kotlin'
    main.java.srcDirs += 'src/main/java'
}

mainClassName = 'demo.MainKt'
defaultTasks 'run'

eos

File.write "#{name}/build.gradle", build_content

main_content = <<-eos
package demo

fun main(args: Array<String>) {
    println("Hello, Kotlin")
}

eos

sh "mkdir -p #{name}/src/main/kotlin/demo"
File.write "#{name}/src/main/kotlin/demo/Main.kt", main_content

gitignore_content = <<eos
.gradle
build/

# Ignore Gradle GUI config
gradle-app.setting

# Avoid ignoring Gradle wrapper jar file (.jar files are usually ignored)
# !gradle-wrapper.jar

# Cache of project
.gradletasknamecache

.idea
*.iml

.settings
.classpath
.project

eos
File.write "#{name}/.gitignore", gitignore_content

sh "cd #{name}; tree"
