#!/bin/bash

PROJECT_NAME=$1

if [[ $PROJECT_NAME = "" ]]; then
  read -p "Project Name:" var
  PROJECT_NAME=$var
fi

if [[ $PROJECT_NAME = "" ]]; then
  echo "Project Name is empty, use default 'rust-empty'"
else
  echo "Project Name: $PROJECT_NAME"
fi

git clone --depth=1 https://github.com/bvssvni/rust-empty.git $PROJECT_NAME
cd $PROJECT_NAME;
rm -rf .git

make cargo-exe
make run
