#!/bin/bash


function display_svn() {
   echo '
   格式: svn propset svn:global-ignores filelist .
   格式: svn propset svn:ignore filePattern .

   $ svn propget svn:ignore backend
   $ svn pg svn:ignore backend
   $ svn pg svn:global-ignores
   $ svn status --no-ignore | grep "^I"
   $ svn pg svn:global-ignores . -v --show-inherited-props

   $ svn propset svn:ignore "*.pem" .
   $ svn propset svn:ignore "1.pem 2.pem " .
   $ svn propset svn:ignore -RF /root/svn-ignore.txt .

   $ svn proplist -v

   links: http://139.199.4.119/book/learn/scm/svn.html
   '
}

function display_ssh() {
    echo '
    $ ssh -p 22 user@host
    $ ssh -p 12367 -fNTL 8162:localhost:8161 user@host
    '
}

function display_git() {
    echo '
    TODO
    '
}

function display_mysql() {
    echo '
    TODO
    '
}

function display_docker() {
    echo '
    TODO
    '
}

function display_jmap() {
    echo '
    TODO
    '
}


function display_jstack() {
    echo '
    TODO
    '
}


function display_jstat() {
    echo '
    TODO
    '
}

function display_top() {
    echo '
    TODO
    '
}

function display_ps() {
    echo '
    TODO
    '
}

function display_sbt() {
    echo '
    links: https://github.com/foundweekends/giter8/wiki/giter8-templates

    sbt -Dsbt.version=1.0.3 new https://github.com/akka/akka-http-scala-seed.g8
    sbt new scala/scala-seed.g8
    sbt new scala/scala-seed.g8
    sbt new scala/hello-world.g8
    sbt new Daxten/bay-scalajs.g8
    sbt ne vmunier/akka-http-scalajs.g8
    sbt new akka/akka-scala-seed.g8
    sbt new akka/akka-java-seed.g8
    sbt new akka/hello-akka.g8
    sbt new playframework/play-scala-seed.g8
    sbt new playframework/play-java-seed.g8
    sbt new lagom/lagom-scala.g8
    sbt new lagom/lagom-java.g8 
    sbt new scala-native/scala-native.g8
    sbt new scala-native/sbt-crossproject.g8
    sbt new http4s/http4s.g8

    sbt new holdenk/sparkProjectTemplate.g8
    sbt new spark-jobserver/spark-jobserver.g8 
    sbt new joost-de-vries/play-angular-typescript.g8
    sbt new joost-de-vries/play-reactjs-typescript.g8
    sbt new ScalaWilliam/akka-stream-kafka-template.g8
    sbt new liquidarmour/akka-http-docker.g8

    sbt new djspiewak/base.g8
    sbt new anvie/multiproject.g8
    '
}

function display_docker_compose() {
    echo '
    docker-compose exec activemq /bin/bash
    docker-compose logs -f --tail=200 activemq
    docker-compose exec activemq /bin/bash -c "tail -f -n 1000 /var/log/activemq/activemq.log"
    '
}

case "$1" in
  svn)  display_svn ;;
  ssh)  display_ssh ;;
  git)  display_git ;;
  mysql) diplay_mysql ;;
  docker) diplay_docker ;;
  jmap) display_jmap ;;
  jstack) display_jstack ;;
  jstat) display_jstat ;;
  top) display_top ;;
  ps) display_ps ;;
  sbt) display_sbt ;;
  docker-compose) display_docker_compose ;;

  *)  echo "tips svn| ssh | git | mysql | jmap | jstack | jstat | top | ps | sbt | docker-compose" ;;
esac
