#!/bin/bash

function after_my() {
    xdg-open http://139.199.4.119/book/
}

function after_bash() {
   xdg-open "https://learnxinyminutes.com/docs/bash/"
}

function usage() {
    echo 'Usage:
$ tip bash | top | ps | du | systemctl | ulimit | egrep | grep | tail | watch | date
    jmap | jstack | jstat | keytool | sbt
    curl | svn | ssh | git | mysql | dot | xclip | iconv | rg 
    docker | docker-compose
    realize | dep | npm | n
    go | go_nil
    cargo | rustup
    consul | nginx
    buffalo
    centos
    semantic_version | uml
    my'
}

###################################
_fn_exists() {
    declare -f -F $1 > /dev/null
    return $?
}

_try_fn() {
   _fn_exists "$1" && eval "$1"
}

task="$1"

if [ -z "$task" ]; then
  usage
else
  ROOT_DIR=$(dirname "$0")
  f="$ROOT_DIR/data/tip/$task.md"
  if [ -e "$f" ]; then
    printf ">read %s\n...\n" "$f"
    _try_fn "before_$1"

    cat "$f"
    printf "\n\n"

    _try_fn "after_$1"
  else
    usage
  fi
fi
