#!/usr/bin/env ruby

def browser(link)
  if RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/
    system "start #{link}"
  elsif RbConfig::CONFIG['host_os'] =~ /darwin/
    system "open #{link}"
  elsif RbConfig::CONFIG['host_os'] =~ /linux|bsd/
    system "xdg-open #{link}"
  end
end

if __FILE__ == $0
  wls = ["https://twitter.com/",
    "http://www.reddit.com/r/rust",
    "https://github.com/stars?direction=desc&sort=updated",
    "http://getprismatic.com/",
    "http://www.douban.com",
    "http://www.weibo.com",
    "http://www.deftype.com",
    "http://bbs.szhome.com/30017.html"]

    wls.reverse.each do |wl|
      browser(wl)
    end

    exit 0
end
